### ISSUE TITLE
Please help keep getting this error

### ISSUE THREAD

**Issue by Hunter11Beast** [walmat/link-builder#1]
throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\link-builder-master\link-builder-master\index.js:1:79)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by walmat** [comment]
Have you went through all the steps in the README? Sounds like to me you haven't ran `npm install` yet.

**Comment by Hunter11Beast** [comment]
Yes I did, I ran npm install. I’ll delete everything and retry it

**Comment by walmat** [comment]
Okay. If you need help further, message me on Discord. @walmat#5572

**Comment by Hunter11Beast** [comment]
Hey, can you sign this petition? https://chn.ge/2Iqa9C5

Thanks! - Hunter
